### ISSUE TITLE
Does not log when moving a category

### ISSUE THREAD

**Issue by freestream** [firegento/firegento-adminmonitoring#11]
It does not add an event to the history when i move a category from one position to another.

From:
![screen shot 2015-01-23 at 08 08 38](https://cloud.githubusercontent.com/assets/5450032/5870997/11dfa518-a2d7-11e4-90ed-b34180b62b91.png)

To:
![screen shot 2015-01-23 at 08 09 11](https://cloud.githubusercontent.com/assets/5450032/5871000/23d1f4ba-a2d7-11e4-9048-ab0195d9cde0.png)

**Comment by therouv** [comment]
Feature implemented in d9547d9
