### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by shumaise** [firegento/firegento-adminmonitoring#22]
Hi

Is there a way to monitor logout of admin.

**Comment by Schrank** [comment]
I don't think logout is implemented. Beside this you can only log, when one is logging out eplicitly. You can't log when session times out easily

**Comment by therouv** [comment]
Hi @shumaise unfortunately Magento does not provide any events during the logout process. We could observe the controller predispatch but as @Schrank mentioned: if the session times out, we could not log any logout. I'd be happy to merge any PR of you which solves your request. 

Side note: My personal opinion is, that monitoring the login is far more important than the logout.
