### ISSUE TITLE
Monitoring the rest api 

### ISSUE THREAD

**Issue by ThiagoNP** [firegento/firegento-adminmonitoring#23]
Is there any way to enable monitoring of the rest api?

**Comment by therouv** [comment]
Hi @ThiagoNP unfortunately, this is currently not possible. 
If you'd create a pull request with the functionality, I'd be happy to merge it.

**Comment by ThiagoNP** [comment]
I implemented this feature on my store, but I don't know if  there is a way to implement this in the module.
What I ended up doing was:
- Changed the module to allow the user who done the action to be passed in the event;
- Changed the module to listen to a custom event I created;
- Created a new api endpoint that dispatch the event with the object and the current api user.

I had to do this because when the `FireGento_AdminMonitoring_Model_Observer_Log` class tried to save a new history entry, generated by an api modification, the admin session didn't return an user. And because of that, it tried saving an entry with user id set to 0, and this silently fails.
