### ISSUE TITLE
Bug: Extension is breaking REST API 

### ISSUE THREAD

**Issue by logeecom** [firegento/firegento-adminmonitoring#25]
When extension is installed and active, REST API is not working properly. Authentication passes as expected but issuing any GET request breaks. For example, calling GET on `/api/rest/products` and Magento is giving this response:
```
{
	"messages" : {
		"error" : [
			{
				"code" : 401,
				"message" : "oauth_problem=internal_error&message=SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mg82_oauth_nonce.nonce_id' in 'where clause', query was: SELECT `mg82_oauth_nonce`.* FROM `mg82_oauth_nonce` WHERE (`mg82_oauth_nonce`.`nonce_id`='0')"
			}
		]
	}
}
```

Here is a request:
![image](https://user-images.githubusercontent.com/20204230/29713662-f8e64d98-899f-11e7-9948-6061c11d84d1.png)

When extension is disabled, everything works as expected.

**Comment by krombox** [comment]
Confirmed. After debugging found that disabling this extension back REST API to live

**Comment by roman204** [comment]
this is cause the extension tries to log history of Mage_Oauth_Model_Nonce

**Comment by Schrank** [comment]
Thanks @roman204 for debugging! If someone provides a PR, we can merge it :-)

Solution should be easy: Just blacklist `Mage_Oauth_Model_Nonce `  in config.xml
