### ISSUE TITLE
Does not log modifications to Permissions

### ISSUE THREAD

**Issue by peterjaap** [firegento/firegento-adminmonitoring#26]
Weirdly enough, this extension does not log changes in Permissions / Roles.

Also, it does not log creation/deletion/modification of Permissions / Users.

**Comment by peterjaap** [comment]
I have identifed the saving of the user is being skipped due to a hardcoded exclude in https://github.com/firegento/firegento-adminmonitoring/blob/develop/src/app/code/community/FireGento/AdminMonitoring/etc/adminmonitoring.xml#L7

@therouv what is the reasoning behind this?

**Comment by peterjaap** [comment]
See #27

**Comment by kkrieger85** [comment]
PR merged
